#!/usr/bin/env python3
"""A plan that contains code must ASSEMBLE into that code, and its evidence must be RUN.

    python3 scripts/check-plan-code.py <plan.md>            # assemble, run suites + mutations
    python3 scripts/check-plan-code.py <plan.md> --evidence # ...and print the evidence block
    python3 scripts/check-plan-code.py --self-test          # 12 cases

WHY THIS EXISTS. Three adversarial review rounds on the project-dashboard plan each
found that its stated evidence was wrong, and each found it BY HAND:

  r2  a transcription silently dropped one word from an assertion, and the
      coordinator reported 55/55 against a test it had weakened.
  r3  the plan's blocks did not assemble at all — no import block for one file, no
      `__main__` dispatch for the other, three functions present only as prose. Every
      earlier reviewer had injected the missing pieces into a private harness, so the
      hole survived two rounds. The plan's own evidence read `19/19 mutations caught`
      while a mutation it NAMED survived, and `33 symbols byte-identical` against
      files nobody else could open.

The pattern, in the r3 reviewer's words: *everything the plan says about CODE
reproduced exactly; everything it says about its own VERIFICATION did not.* Prose
about a measurement is not the measurement. `docs/dev-process.md` gives the remedy —
"before adding a rule, ask whether it can be a script" — so the evidence block is now
GENERATED by this script and pasted, never typed.

⚠ WHAT THIS DOES NOT DO, stated rather than discovered: it proves the assembled files
import, self-test, and fail under the declared mutations. It cannot prove the plan's
PROSE is right, that the mutation list is complete, or that a passing case is
meaningful. An undeclared mutation is invisible to it — which is why the manifest
lives in the plan under review, where a reviewer reads it.

CONTRACT. In the plan, tag each Python block with the file it belongs to:

    <!-- file: gen-dashboard.py -->
    ```python
    ...
    ```

Blocks with the same tag are concatenated in document order. Declare mutations in one
JSON block tagged `<!-- mutations -->`; each needs a `name`, a `file`, a list of
`edits` (find/replace pairs applied in order, each of which MUST match), and
optionally `expect` — a substring of the self-test case name that has to go red.
"""
from __future__ import annotations
import argparse
import json
import pathlib
import re
import subprocess
import sys
import tempfile

FILE_TAG = re.compile(r"<!--\s*file:\s*([A-Za-z0-9._/-]+)\s*-->")
MUT_TAG = re.compile(r"<!--\s*mutations\s*-->")
FENCE = re.compile(r"^```(\w*)\s*$")


def extract(md: str) -> tuple[dict[str, list[str]], list[dict], list[str]]:
    """(files -> blocks, mutations, problems). A tag with no block that follows is a
    problem, not a silent skip — that is how a plan loses a function to prose."""
    lines, files, muts, problems = md.split("\n"), {}, [], []
    pending, want_mut, i = None, False, 0
    while i < len(lines):
        line = lines[i]
        if (m := FILE_TAG.search(line)):
            if pending:
                problems.append(f"file tag for {pending!r} was followed by another tag, not a block")
            pending, want_mut = m.group(1), False
        elif MUT_TAG.search(line):
            if pending:
                problems.append(f"file tag for {pending!r} was followed by the mutations tag")
            pending, want_mut = None, True
        elif (f := FENCE.match(line)):
            body, i = [], i + 1
            while i < len(lines) and not FENCE.match(lines[i]):
                body.append(lines[i])
                i += 1
            text = "\n".join(body)
            if pending:
                if f.group(1) != "python":
                    problems.append(f"block for {pending!r} is tagged ```{f.group(1)}, not ```python")
                files.setdefault(pending, []).append(text)
                pending = None
            elif want_mut:
                try:
                    muts.extend(json.loads(text))
                except json.JSONDecodeError as exc:
                    problems.append(f"mutations block is not valid JSON: {exc}")
                want_mut = False
        i += 1
    if pending:
        problems.append(f"file tag for {pending!r} has no code block after it")
    if want_mut:
        problems.append("mutations tag has no JSON block after it")
    return files, muts, problems


def run_suite(d: pathlib.Path, name: str) -> tuple[int, str]:
    r = subprocess.run([sys.executable, name, "--self-test"], cwd=d,
                       capture_output=True, text=True, timeout=120)
    return r.returncode, (r.stdout + r.stderr).strip()


def check(plan: pathlib.Path) -> tuple[bool, list[str], dict]:
    md = plan.read_text(encoding="utf-8")
    files, muts, problems = extract(md)
    report, ev = list(problems), {"files": {}, "mutations": [], "survivors": []}
    if not files:
        report.append("no `<!-- file: … -->` tagged Python blocks found — nothing to assemble")
        return False, report, ev

    with tempfile.TemporaryDirectory() as td:
        d = pathlib.Path(td)
        for name, blocks in files.items():
            (d / name).parent.mkdir(parents=True, exist_ok=True)
            (d / name).write_text("\n\n".join(blocks) + "\n", encoding="utf-8")
        ok = not problems
        for name in files:
            rc, out = run_suite(d, name)
            tail = out.split("\n")[-1] if out else "(no output)"
            ev["files"][name] = {"rc": rc, "tail": tail, "blocks": len(files[name])}
            if rc != 0:
                ok = False
                report.append(f"{name}: --self-test exited {rc}\n    {out[-600:]}")
            elif "passed" not in out:
                ok = False
                report.append(f"{name}: --self-test exited 0 but printed no result — "
                              f"a script with no entrypoint exits 0 silently. Got: {tail!r}")

        for mut in muts:
            name, fname = mut.get("name", "?"), mut.get("file", "")
            if fname not in files:
                ok = False
                report.append(f"mutation {name!r} targets unknown file {fname!r}")
                continue
            src = (d / fname).read_text()
            for find, repl in mut.get("edits", []):
                if find not in src:
                    ok = False
                    report.append(f"mutation {name!r}: anchor NOT FOUND — it was not applied, "
                                  f"so its 'caught' verdict would be meaningless")
                    src = None
                    break
                src = src.replace(find, repl, 1)
            if src is None:
                continue
            orig = (d / fname).read_text()
            (d / fname).write_text(src)
            rc, out = run_suite(d, fname)
            (d / fname).write_text(orig)
            fails = [l.strip()[7:].split(":")[0] for l in out.split("\n") if "[FAIL]" in l]
            caught = rc != 0
            want = mut.get("expect")
            named = (not want) or any(want in f for f in fails)
            ev["mutations"].append({"name": name, "caught": caught, "fails": fails})
            if not caught:
                ok = False
                ev["survivors"].append(name)
                report.append(f"mutation SURVIVED — {name}: the suite stayed green, so no case "
                              f"can fail for what it names")
            elif not named:
                ok = False
                report.append(f"mutation {name!r} went red, but not via a case matching "
                              f"{want!r} — it was caught by something else: {fails}")
    return ok, report, ev


def evidence(ev: dict) -> str:
    out = ["```", "GENERATED by scripts/check-plan-code.py — do not edit by hand.", ""]
    for name, f in sorted(ev["files"].items()):
        out.append(f"  {name:28} {f['blocks']:>2} blocks assembled -> {f['tail']}")
    caught = sum(1 for m in ev["mutations"] if m["caught"])
    out.append("")
    out.append(f"  mutations declared and run: {len(ev['mutations'])}, caught {caught}")
    for m in ev["mutations"]:
        out.append(f"    {'caught  ' if m['caught'] else 'SURVIVED'} {m['name']}")
    out.append("```")
    return "\n".join(out)


def _self_test() -> int:
    ok = fail = 0

    def case(name, got, want):
        nonlocal ok, fail
        if got == want:
            ok += 1
        else:
            fail += 1
            print(f"  [FAIL] {name}: got {got!r} want {want!r}")

    # The fixture emits a real [FAIL] line, so the `expect` path is genuinely
    # exercised rather than passing because the list is empty.
    GOOD = ('<!-- file: m.py -->\n```python\ndef f():\n    return 1\n\n\n'
            'def _self_test():\n'
            '    bad = f() != 1\n'
            '    if bad:\n'
            '        print("  [FAIL] f returns one: got %r" % f())\n'
            '    print("%d/1 passed" % (0 if bad else 1))\n'
            '    return 1 if bad else 0\n\n\n'
            'import sys\nif __name__ == "__main__":\n    sys.exit(_self_test())\n```\n')
    MUTS = ('<!-- mutations -->\n```json\n'
            '[{"name": "f returns 2", "file": "m.py", "edits": [["return 1", "return 2"]],'
            ' "expect": "f returns one"}]\n```\n')

    files, muts, probs = extract(GOOD + MUTS)
    case("one file extracted", list(files), ["m.py"])
    case("one mutation extracted", len(muts), 1)
    case("no problems on a well-formed plan", probs, [])

    _, _, p = extract('<!-- file: a.py -->\n<!-- file: b.py -->\n```python\nx = 1\n```\n')
    case("a tag followed by another tag is a problem", len(p), 1)
    _, _, p = extract("<!-- file: a.py -->\nno block follows\n")
    case("a tag with no block is a problem", len(p), 1)
    _, _, p = extract('<!-- file: a.py -->\n```bash\necho hi\n```\n')
    case("a non-python block under a file tag is a problem", len(p), 1)
    _, _, p = extract('<!-- mutations -->\n```json\nnot json\n```\n')
    case("an unparseable mutations block is a problem", len(p), 1)

    with tempfile.TemporaryDirectory() as td:
        pl = pathlib.Path(td) / "p.md"
        pl.write_text(GOOD + MUTS)
        good_ok, rep, ev = check(pl)
        case("a well-formed plan passes", good_ok, True)
        case("its mutation is recorded as caught", ev["mutations"][0]["caught"], True)

        # A script with no entrypoint exits 0 and prints nothing — r3's Blocking.
        pl.write_text('<!-- file: m.py -->\n```python\ndef f():\n    return 1\n```\n')
        silent_ok, rep, _ = check(pl)
        case("a file with no entrypoint FAILS rather than passing silently", silent_ok, False)
        case("...and says why", any("no entrypoint" in r for r in rep), True)

        # A mutation whose anchor is absent was never applied.
        pl.write_text(GOOD + '<!-- mutations -->\n```json\n'
                      '[{"name": "ghost", "file": "m.py", "edits": [["nope", "x"]]}]\n```\n')
        ghost_ok, rep, _ = check(pl)
        case("a mutation whose anchor is missing FAILS", ghost_ok, False)

        # A mutation that goes red via a DIFFERENT case than the one named is
        # not evidence for the case it claims — r3's day-anchor shape.
        pl.write_text(GOOD + '<!-- mutations -->\n```json\n'
                      '[{"name": "wrong case", "file": "m.py", "edits": [["return 1", "return 2"]],'
                      ' "expect": "some other case"}]\n```\n')
        wrong_ok, rep, _ = check(pl)
        case("a mutation caught by the WRONG case fails", wrong_ok, False)
        case("...and says which case caught it", any("caught by something else" in r for r in rep), True)

        # A surviving mutation must fail the check.
        pl.write_text(GOOD + '<!-- mutations -->\n```json\n'
                      '[{"name": "no-op", "file": "m.py", "edits": [["def f():", "def f():"]]}]\n```\n')
        surv_ok, rep, ev = check(pl)
        case("a SURVIVING mutation fails the check", surv_ok, False)

    print(f"\n{ok}/{ok+fail} passed")
    return 1 if fail else 0


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("plan", nargs="?")
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--evidence", action="store_true")
    a = ap.parse_args(argv)
    if a.self_test:
        return _self_test()
    if not a.plan:
        print("CANNOT RUN — no plan given. Treat this as NOT CHECKED.", file=sys.stderr)
        return 2
    p = pathlib.Path(a.plan)
    if not p.is_file():
        print(f"CANNOT RUN — {p} does not exist. Treat this as NOT CHECKED.", file=sys.stderr)
        return 2
    ok, report, ev = check(p)
    for r in report:
        print(f"  ✗ {r}")
    if a.evidence:
        print(evidence(ev))
    print(("OK — " if ok else "FAILED — ") + f"{len(ev['files'])} file(s), "
          f"{len(ev['mutations'])} mutation(s), {len(ev['survivors'])} survivor(s)")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
